id: P8853F829
initial_creation_type: input
source_metadata:
  title: Words of the Buddha
  language: en
  description: 'A selection of works by the Buddha himself, many of which feature
    in the Kangyur (bka'' ''gyur), the Tibetan canonical collection of the Buddha''s
    Word:'
  volume:
    3c3212077826426e80919b917fc29466:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Auspiciousness
    3d87e8b948a54a4a9f6ef5918acd425f:
      title: The Dhāraṇī of Amitāyus
      parent: Dhāraṇī
    1c2fe55cb7da4219a938f072a88ab567:
      title: The Dhāraṇī of Glorious Vajraṇakhī
      parent: Dhāraṇī
    e78c9fb877bd4f19af0083deda41c719:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Dhāraṇī
    47a3387f38b640d0a077205e1deeb899:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Dhāraṇī
    5dec217e42b1459a931ba515fc26fbe7:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    ac809f88ebcc45ec8a53819a2933aa45:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    85d308746ba34f30afdf69c667835c7c:
      title: The Noble Mārīcī Dhāraṇī
      parent: Dhāraṇī
    d7ceff3f70c54c7c8fdb477804577fbc:
      title: Vajravidāraṇa Dhāraṇī (Nyingma Version)
      parent: Dhāraṇī
    18986941d5394b8882fb2fb387bc55a9:
      title: Prayer for the Future of the Dharma
      parent: Prayers
    d277b3cc540d47388120207454548c44:
      title: 'The Clarifying Light: A Prophecy of the Future'
      parent: Prophecy
    af0418c4f3d64853a2637442567f5ce1:
      title: The Song of the Vajra
      parent: Songs
    e60867e4c0dd4841a571ef84be1e7d97:
      title: Maitreya's Aspiration
      parent: Sūtra
    320dc3593e394cf7b311c1d340a3e526:
      title: The Bodhisattva’s Confession of Downfalls (Nyingma Version)
      parent: Sūtra
    ed38af5cb90e4b78a8d7a10bafd24cb7:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtra
    0c55388266414deda6fbb6ed786823f1:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Sūtra
    3083e7ba47dd402aa67727a65b5cef4c:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtra
    55a90c284254407c9bdd44faa99bf0fb:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Sūtra
    c11c0ca15dd846998f281d6c0f82966f:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Sūtra
    45cd0aefdb804892a19bf917fab52a69:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Sūtra
    663b513123b94125b337d8c606a901bb:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtra
    4911f07274534d67a02596014b61b319:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    7d479198ff224d1bbaca441bcd31a999:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    988811c6bf3a4269a8fe3527dd8c38ca:
      title: Daily Confession (from the Vajrapañjara Tantra)
      parent: Tantra
    31937271b4284ec2ae38529f7512fa0d:
      title: The Lament of Rudra
      parent: Tantra
    6081f18d7f6948859bc653871266efae:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tantra
    490b8a248f2b43aca4df464ffbd27f22:
      title: The Twenty-Eight Commitments
      parent: Tantra
    35bfa136e2114f9395c519bc2af6871b:
      title: The Ultimate Inexpressible Confession (Yeshe Kuchokma)
      parent: Tantra
    802eede7204449f2b0062902b30b4c41:
      title: Verses of Confession 'Düsum Deshekma'
      parent: Tantra
created_at: '2022-03-01T02:07:32.758519'
last_modified_at: '2022-03-01T02:07:32.758526'
